name: PoliceRP
version: '${version}'
main: cz.hesovodoupe.policerp.PoliceRP
api-version: '1.19'
authors: [Heso]
description: Command for POLICE RP
website: snezik.cz

commands:
  prestupek:
    description: Potrestej hrace za prestupek
    usage: /<command> [nick]
    permission: policerp.punish
    permission-message: "Na tohle nemáš práva!"
  propustit:
    description: Propust hráče z jailu
    usage: /<command> [nick]
    permission: policerp.punish
    permission-message: "Na tohle nemáš práva!"
  nabor:
    description: Nabrat do práce
    usage: /<command> [ems/pd/fire/army] [nick]
    permission: policerp.chief
    permission-message: "Na tohle nemáš práva!"
  vyhazov:
    description: Vyhodit z práce
    usage: /<command> [ems/pd/fire/army] [nick]
    permission: policerp.chief
    permission-message: "Na tohle nemáš práva!"

permissions:
  policerp.punish:
    description: "Slouží pro policejní složky"
    default: false
  policerp.chief:
    description: "Slouží pro vedení policie"
    default: false
  firerp.chief:
    default: false
  ems.chief:
    default: false