name: PoliceRP
version: '${version}'
main: cz.hesovodoupe.policerp.PoliceRP
api-version: '1.19'
authors: [Heso]
description: Command for POLICE RP
website: snezik.cz

commands:
  felony:
    description: Felony player
    usage: /<command> [nick]
    permission: policerp.punish
    permission-message: "You dont have permissions!"
  propustit:
    description: Propust hráče z jailu
    usage: /<command> [nick]
    permission: policerp.punish
    permission-message: "Na tohle nemáš práva!"
  hire:
    description: Hire to job
    usage: /<command> [ems/pd/fire/army] [nick]
    permission: policerp.chief
    permission-message: "You dont have permissions!"
  fire:
    description: Fire from job
    usage: /<command> [ems/pd/fire/army] [nick]
    permission: policerp.chief
    permission-message: "You dont have permissions!"
  license:
    description: Info about players license
    usage: /<command> [show/set] [nick]
    permission: policerp.punish
    permission-message: "You dont have permissions!"

permissions:
  policerp.punish:
    description: "Slouží pro policejní složky"
    default: false
  policerp.chief:
    description: "Slouží pro vedení policie"
    default: false
  firerp.chief:
    default: false
  ems.chief:
    default: false